<article class="article blog">
	<h2 class="text-center text-3xl lg:text-6xl">Kokostezky trail</h2>
	<div class="blog-article py-12">
		<p>Vážení příznivci a návštěvníci Kokostezek,</p>
		<p>Na letošní rok jsme pro vás připravili změny v trailovém okruhu a vzhledem k tomu, že na Kokostezkách značku v lese nenajdete a trasa okruhu se několikrát kříží, určitě pro vás budou následující informace užitečné.</p>
		<p>Ti z vás, kteří už si v minulosti projeli Základní okruh, budou většinu trailů poznávat, ale narazí i na nové pasáže.</p>
		<p>Naše doporučení tedy zní: “Přečtěte si následující text v kombinaci s mapou, ať víte, co vás čeká a bloudění vám zbytečně nezkomplikuje vaši jízdu. Na cestu se vydejte s GPX souborem v navigaci, nebo alespoň s okruhem v mapy.cz ve vašem telefonu“.</p>
		<p>Začínáme v ATC Kokořín, kde buď můžete zaparkovat, nebo přijet na kole v případě, že jste si vybrali jiné parkoviště v Kokořínském Dole nebo blízkém okolí. Lesní cestu, která vede z kempu, opustíte na první křižovatce doprava prudkým krátkým stoupáním, které je pro někoho výjezdová výzva a pro někoho úsek, kde se projde vedle kola. Dalším odbočením doprava se dostanete na vrstevnici – trail s názvem <strong> 2.patro</strong>, který vede zpět na silnici k rybníku Kačírek. S rybníkem po pravé ruce pokračujete pár stovek metrů po silnici a u hospody U Grobiána (místo prvního křížení trasy) odbočíte doleva a stále po silnici začnete stoupat směrem k obci Kanina kam ale nedojedete a přibližně ve dvou třetinách stoupání odbočíte doprava mezi skály a ve stoupání už pokračujete mimo asfalt. Po dalších stovkách metrů odbočíte znovu doprava na štěrkovou cestu a podél pole po levé ruce dojedete až na kraj lesa, kde vlevo od schodů z železničních pražců, najedete na trail s názvem <strong>Levandule</strong>. Levandule začíná technickým sjezdem s několika uzavřenými zatáčkami a přes dřevěnou lávku se napojíte na houpavou vrstevnici a po ní zase zpět do údolí. Na konci sjezdu a po odbočení doleva už zase stoupáte, abyste se po dalším vrstevnicovém trailu zvaném <strong>Blaženka</strong> zakončeném sjezdem k silnici, dostali na Harasov, místo na občerstvení a možná i osvěžení v místním rybníce.</p>
		<p>Okruh pokračuje po hrázi rybníka a na jejím konci odbočíte na cestu vlevo. Na pravé straně si můžete prohlédnout reliéfy v pískovcových skalách a na dalším dělení cest se dáte doprava k trailu Harakoko. Další důkaz, že „trail“ v terminologii Kokostezek, neznamená jízdu z kopce. <strong>Harakoko</strong> je pohodová vrstevnice, která prochází stejnojmennou chatovou osadou, po které se přiblížíte zpět ke Kokořínskému Dolu. Na konci tohoto úseku se dáte doleva a stoupacím trailem se vyškrábete na asfaltovou cestu mezi poli zvanou <strong>Eurocesta</strong>. Po výjezdu z lesa se doprava po asfaltu dostanete do Janovi Vsi a opět doprava již po silnici do obce Kokořín. V Kokoříně se dáme před zámkem doprava a hned za poslední zámeckou budovou vlevo již najíždíte na trail <strong>Staráky</strong>. A opět vrstevnice, tentokrát s technickými prvky, vás dovede až na silnici k hradu Kokořín. Přibližně v první třetině Staráků je technické místo nově obohaceno o schody, které chrání kořenový systém výrazně odhalen ježděním v průběhu posledních let. Schody jsou primárně pro pěší a ukázalo se, že jejich sjížděním se ničí. Slezte, prosím, z kola a než pro vás připravíme náhradní a věříme, že jistě zábavnou lajnu, po schodech nejezděte. Od schodů pokračujete doleva po vrstevnici, která vás určitě bude bavil, ale zároveň vám nedá vydechnout. Po sjezdu po silnici okolo hradu vás čeká odpočinková pasáž. Od restaurace Pobuda, kde se opět můžete občerstvit, vás čeká úsek asi 3 km po silnici do Vojtěchova. Není to zábava, ale nutný transfer na přiblížení se k dalším trailům.</p>
		<p>Z Vojtěchova začínáme nejprve pozvolným, ale ke konci již strmějším stoupáním <strong>Boudeckou roklí</strong> k dalším atrakcím Kokořínska. Skalní útvary, které připomínají Obří hlavu a Žábu, když se na ně díváte pod tím správným úhlem. Po cyklostezce vedoucí velice atraktivním místem s názvem Průsečná skála pokračujeme na další trail, na který najedeme těsně před vrcholem stoupání prudce doprava. <strong>Žlabožrout</strong> je svižný trail, který se zhruba ve své polovině dělí na snazší a obtížnější verzi, která trailu dala název a žlab na konci už sežral nejednoho bikera. Lehčí varianta jistě není takovou výzvou, ale to jí nic neubírá na atraktivnosti. Obě varianty vás přivedou na modrou turistickou značku do rokle zvané <strong>Močidla</strong> a pokračujete doleva mírným stoupáním, stále po modré turistické značce, kterou před závěrečnou „stojkou“ opustíme a spíše stoupacím trailem <strong>Hrachové pole</strong>, se dostaneme až na silnici za Sedlec (druhé křížení trasy). Ze silnice odbočíme u Kříže doprava a po zelené turistické značce směřujeme k dalšímu trailu. Na <strong>Milču</strong> najedete v úseku, kdy se vám to docela slušně rozjede a v mírné levotočivé zatáčce je třeba trefit vyježděnou pěšinu vpravo, po které pokračujete na hraně lesa a pole, abyste se zhruba po 1 km zanořili hlouběji do lesa a užili si druhou – sjezdovou část <strong>Milči</strong>.</p>
		<p>Sjezd končí na červené turistické značce v Kokořínském údolí, proto je potřeba jet rozumně, a hlavně nevletět mezi turisty! Tento úsek je pěšími turisty v sezóně jaro až podzim a o víkendech hodně využíván a vzhledem k tomu, že po ní budete pokračovat, buďte zdvořilí a ohleduplní a připomeňte si jedno z našich pravidel <strong>"Pozdrav a poděkuj"</strong>.</p>
		<p>Červená vás dovede znovu ke Grobiánovi odkud se vydáte podobně jako na začátku okruhu po silnici směr Kanina, ale před začátkem stoupání odbočíte přes parkoviště po levé straně na trail, který vede rovnoběžně s červenou turistickou značkou a napojí se na ní na rozcestí před Vrbodolem. Pokračujete doleva do <strong>Kočičiny</strong> a po červené vyjedete do Sedlce, kde už jste dnes byli. Ze silnice ale neodbočujete u kříže na zelenou a pokračujete až do Hradska. Touto vískou projedete rovně a po žluté turistické značce spadnete po pískovcových schodech k začátku posledního trailu dne – <strong>Cámburku</strong>. Schody jsou další místo, kde je důležitá opatrnost a obezřetnost. Zkontrolujte, prosím, jestli se na schodech někdo není a počkejte, až budete mít volno pro vaši jízdu. Jde o úzkou soutěsku a v případě setkání jedoucího cyklisty a pěšího turisty se není kam vyhnout. Po opuštění skalních stěn do otevřeného lesa opustíte žlutou značku a po odbočení doprava již tradičním vrstevnicovým trailem se závěrečným sjezdem dojedete do místa, kde jste vaše putování po Kokostezkách začínali. <strong>Cámburk se spojí s 2.patrem</strong> a dojedete na silnici kousek od vjezdu do ATC Kokořín.</p>
		<p>Z popisu je patrné, že mnoho „enduro“ zábavy si neužijete. Kokostezky jsou přírodní stezky, kde se neustále střídají výjezdy, vrstevnice a sjezdy, na kterých funguje plynulá jízda, pomalá technika, rovnováha a předvídavost. Okruh je fyzicky náročný s technicky zajímavými úseky a přírodními zajímavostmi, u kterých jistě stojí zato, si přibrzdit.</p>
		<p>Kokořínské stezky nejsou klasické uzavřené trail centrum s nově budovanými traily, ale snahou o využití stávajících, případně původních a zanikajících cest a cestiček, na kterých nebudete sami. Kokořínsko je atraktivní lokalita, do které přijíždí stále více návštěvníků, které budete potkávat nejen na turistických trasách, ale i na trailech Kokostezek. Buďte, prosím, ohleduplní k ostatním turistům, přírodě, trailům i místním obyvatelům. Budete se tak podílet na zvyšování kvality soužití tohoto „organismu“.</p>
		<p>Děkujeme a těšíme se na vás</p>
		<p>Vaše Kokostezky</p>
		<div class="mapa my-8 md:my-24 text-center">
			<h4>Koko trail</h4>
			<p>43km, alt.999m<br /><a href="https://en.mapy.cz/zakladni?x=14.5893207&y=50.4352335&z=14&dim=608e58413c505e56853b3207" target="_blank" class="underline m-4">mapy.cz</a>
				<br /><a href="./gpx/Kokostezky-trail_2021.gpx" target="_blank" class="underline m-4">gpx soubor</a>
			</p>
			<img src=" ./img/qr_Kokostezky_trail_2021.png" class="img-responsive max-w-xs mx-auto">
		</div>

	</div>
</article>